### ISSUE TITLE
Add playback rate options

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#18]
Request from @julianchandra

**Comment by tsheaff** [comment]
I researched this one in depth today, since this would be a great feature and save users collectively many thousands of hours listening to podcast type of videos.

The `AVPlayerViewController` really doesn't provide any UI customization on the controls, so we'd either need to:

1) Implement our own custom video player controls. This may be a good idea eventually, since being in full control of the core UX of the video playback which is so central to Odysee may make sense. However it's a big lift. Here are a few libraries I think could do the trick to get us started (and then we could always fork those if we need additional customization:
  - [`ASPVideoPlayer`](https://github.com/andreipitis/ASPVideoPlayer)
  - [`mobileplayer-ios`](https://github.com/sahin/mobileplayer-ios)
  - [`piemonte/Player`](https://github.com/piemonte/Player) has a nice UI with good delegate methods, but there are no UI controls so we'd need to implement the scrubber, play/pause etc. fully ourselves.

Other considerations for this approach are [Picture in Picture](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player), and the lock screen controls.

2) Keep `AVPlayerViewController` and just add a `rate` toggle in the UI outside of the code video controls.

**Comment by tzarebczan** [comment]
Would like to see @akinwale 's comments on this one, thanks for doing the research!
